# Default values for hello-opentelemetry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/sallyom/otel-ex
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: hello

# this matches what is already deployed in otel-dev
tlsSecretName: sample-app-tls
jaegerName: jaegerex

# Note: this is hard-coded in hello_openshift.go, for the otelcollector service address connection 
# TODO: figure out why "0.0.0.0:4317" doesn't work in application code
namespace: otel-dev

# this is <jaeger-name>-collector-headless.<namespace>.svc:14250
# Note: this needs to match the namespace above and what's hard-coded in code
# TODO: fix ^^
jaegerEndpoint: jaegerex-collector-headless.otel-dev.svc:14250

metrics:
  # Disable auth checks when scraping metrics (allow anyone to scrape)
  disableAuth: false


imagePullSecrets: []
nameOverride: ""
fullnameOverride: "sample-app"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  # fsGroup: 2000
  runAsNonRoot: true
  # seccompProfile:
  #   type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

openshift:
  # Force deployment of the SCC even if the api resource isn't detected
  forceSCC: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
