{{- if .Values.serviceAccount.create -}}
{{- $fullName := include "hello-opentelemetry.fullname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hello-opentelemetry.fullname" . }}
  labels:
    app: {{ $fullName }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
